### ISSUE TITLE
[Feature] Authentication to supervisord monitor

### ISSUE THREAD

**Issue by jbfarez** [mlazarov/supervisord-monitor#1]
Hey @mlazarov,

You know, I actually have all my _supervisord_ hosts configured with an authentication on _monitor_ (a basic auth prompted on http connection) : 

```
[inet_http_server]
port=0.0.0.0:9001
username=foo
password=bar
```

My question is : Is there a way to keep my authentication with _supervisord-monitor_ ?

Thanks.

Cheers

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
