### ISSUE TITLE
When using supervisord from a subfolder of the web root js/css cannot be loaded

### ISSUE THREAD

**Issue by DannyvdSluijs** [mlazarov/supervisord-monitor#12]
When using supervisord from a subfolder of the web root js/css cannot be loaded, this is due to the fact that the js and css files are loaded with a leading slash. For a local installation I've added a . (dot) to make the file path relative.

**Comment by mlazarov** [comment]
DannyvdSluijs, please pull latest commit - contains fix for fixed urls

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
