### ISSUE TITLE
All actions are not executed

### ISSUE THREAD

**Issue by flaviomoringa** [mlazarov/supervisord-monitor#20]
I,

the frontpage works very well, but everytime I issue a command it gives-me an error:
Ex:
The requested URL /control/stop/mirror23-obb/lsyncd-obbs:lsyncd-obbs-1357 was not found on this server.

The site is being called from a proxy_pass apache rule on another server, could that be it?

**Comment by mlazarov** [comment]
Hi @flaviomoringa,

your web server isn't respecting the .htaccess file.

You can add `AllowOverride All` to the httpd.conf to test if that is the problem.

For more information see the apache htdocs manual:
https://httpd.apache.org/docs/2.2/mod/core.html#allowoverride

**Comment by flaviomoringa** [comment]
That was it...

thanks for helping... and sorry for the basic question :-)

Keep up the good work

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
