### ISSUE TITLE
Tagged Release

### ISSUE THREAD

**Issue by paulbovbel** [mlazarov/supervisord-monitor#21]
Thanks for this great tool!

Could you please make a tagged release - would like to be able to pull down a stable version of this package for deployment.

**Comment by mlazarov** [comment]
Sure!
Here is it:
https://github.com/mlazarov/supervisord-monitor/releases/tag/v1.0.0

Martin

**Comment by paulbovbel** [comment]
Fantastic, thanks

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
