### ISSUE TITLE
RedMine setup | Can't seem to find out how it works

### ISSUE THREAD

**Issue by zakswindow** [mlazarov/supervisord-monitor#24]
Hi,

Is there anyone can help to setup redmine please? I have setup vhost and i can see the dashboard but 401 unauthorized. Attached an image for you to see.

**I didn't get what is explained here;**
Redmine integration

I didn't get what is explained here;
Redmine integration

1.Open configuration file:

vim application/config/supervisor.php
2.Change this lines with your redmine url and auto assigne id:

**Can you explain a little bit about this?**
// Path to Redmine new issue url
$config['redmine_url'] = 'http://redmine.url/path_to_new_issue_url';
// Default Redmine assigne ID
$config['redmine_assigne_id'] = '69';

**Do I have to install any plugins?**

[Dashboard Screenshot](https://cloud.githubusercontent.com/assets/12625069/16521359/3d28c0ce-3f8e-11e6-81d4-8afb29556911.png)

**Comment by mlazarov** [comment]
Redmine settings are optional - only if you already have Redmine running.

From your screenshot I can see that you missed the supervisord auth config - you didn't setup username&password or they are wrong.

Here are the lines from the config that you should edit:

```php
'server01' => array(
		'url' => 'http://server01.app/RPC2',
		'port' => '9001',
		'username' => 'yourusername',
		'password' => '**yourpass'
	),
```

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
