### ISSUE TITLE
nginx error 500

### ISSUE THREAD

**Issue by FAKERINHEART** [mlazarov/supervisord-monitor#25]
I have nginx config with:
server{
    server_name 10.21.200.75;
    listen 9011;
    root /data/release/server/infras/supervisord-monitor/public_html/;
    index index.php;

```
access_log /data/release/server/infras/supervisord-monitor/public_html/access.log;
error_log  /data/release/server/infras/supervisord-monitor/public_html/error.log;

location / {
    try_files $uri $uri/ /index.php;
}

location ~* \.php$ {
    include fastcgi.conf;
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;
}
```

}

and supervisord-monitor.php with:

// Dashboard columns. 2 or 3
config['supervisor_cols'] = 2;

// Refresh Dashboard every x seconds. 0 to disable
config['refresh'] = 10;

// Enable or disable Alarm Sound
config['enable_alarm'] = true;

// Show hostname after server name
config['show_host'] = true;

config['supervisor_servers'] = array(
    'server01' => array(
        'url' => '10.21.200.75',
        'port' => '9010',
        'username' => 'user',
        'password' => '123'
    ),
);

// Set timeout connecting to remote supervisord RPC2 interface
;config['timeout'] = 3;

// Path to Redmine new issue url
$config['redmine_url'] = 'http://redmine.url/path_to_new_issue_url';

// Default Redmine assigne ID
$config['redmine_assigne_id'] = '69';

**However, when I started the nginx service and go to the 10.21.200.75:9011, it returned error 500.
Could you help me resolve this problem?
Thx~**

**Comment by mlazarov** [comment]
What errors do you have in the error_log?

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
