### ISSUE TITLE
compatibility with php 7.1 ? xmlreader error

### ISSUE THREAD

**Issue by vesper8** [mlazarov/supervisord-monitor#29]
Hrm, so I did solve this problem by installing

sudo apt-get install php7.0-xml

but previously I did have sudo apt-get install php7.1-xml and it was giving me an error that xmlreader extension was not installed. I am running php 7.1

odd that the 7.0-xml works but not the 7.1-xml 

this is kind of a problem because php7.0-xml gets removed if I run autoremove

**Comment by mlazarov** [comment]
*supervisord-monitor* doesn't require any specific version of php nor php-xml.
The php xml module just needs to be loaded.

Your problem looks like php miss-configuration. You can check if you have php-xml loaded by running phpinfo() in php script.

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
