### ISSUE TITLE
Invalid XML form

### ISSUE THREAD

**Issue by daniilsvirin** [mlazarov/supervisord-monitor#33]
Hi! I'm trying to run your app and I'm getting this error:

> The XML data received was either invalid or not in the correct form for XML-RPC. Turn on debugging to examine the XML data further.

I turned on debug mode and this is what I've got:

> ERROR - 2017-07-14 14:04:39 --> Severity: Notice  --> Resource ID#920 used as offset, casting to integer (920) /var/www/html/supervisord-monitor/system/libraries/Xmlrpc.php 1094
ERROR - 2017-07-14 14:04:39 --> Severity: Notice  --> Resource ID#920 used as offset, casting to integer (920) /var/www/html/supervisord-monitor/system/libraries/Xmlrpc.php 950
ERROR - 2017-07-14 14:04:39 --> Severity: Notice  --> Array to string conversion /var/www/html/supervisord-monitor/application/views/welcome.php 75
ERROR - 2017-07-14 14:04:39 --> Severity: Warning  --> Illegal string offset 'group' /var/www/html/supervisord-monitor/application/views/welcome.php 91
ERROR - 2017-07-14 14:04:39 --> Severity: Warning  --> Illegal string offset 'name' /var/www/html/supervisord-monitor/application/views/welcome.php 91
ERROR - 2017-07-14 14:04:39 --> Severity: Warning  --> Illegal string offset 'name' /var/www/html/supervisord-monitor/application/views/welcome.php 92
DEBUG - 2017-07-14 14:04:39 --> Xmlrpc class already loaded. Second attempt ignored.

Do you what can cause this error?

**Comment by mlazarov** [comment]
Check this thread:
https://github.com/mlazarov/supervisord-monitor/issues/17

**Comment by daniilsvirin** [comment]
Thanks.

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
