### ISSUE TITLE
can supervisord-monitor monitoring machine as a group?

### ISSUE THREAD

**Issue by zqc0512** [mlazarov/supervisord-monitor#37]
can supervisord-monitor monitoring machines as a group? 
ie : 
in supervisord-monitor pages  have  groups,  can use the groups to start or stop the processes in groups onces , now is ones can start or stop processes as one server .when have many machines ,this not accepts.

**Comment by mlazarov** [comment]
Currently no but is possible to be extended that way - feel free to post pull request!

**Comment by mlazarov** [comment]
Hey @zqc0512,
you can try this pull request:

https://github.com/mlazarov/supervisord-monitor/pull/48

Martin

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
