### ISSUE TITLE
NO_FILE error 

### ISSUE THREAD

**Issue by najamhaq** [mlazarov/supervisord-monitor#39]
![no_file_error](https://user-images.githubusercontent.com/1304405/32279565-7ea82bf2-beef-11e7-893d-51b098104510.png)

According to RPC docs, NO_FILE error occurs due to permission issues. However in my case, both supervisord log and process logs are owned by root and have 644 permission, so the nginx or rpc should be able to read it.

**Comment by mlazarov** [comment]
Hey najamhaq, you still have permission issue - nginx is not reading the logs.  Supervisord service is the one that is reading them.

**Comment by VStepulo** [comment]
Have the same error. In my case Supervisord and supervisord-monitor runs on different servers.

supervisord log on first server have 0777 permissions
worker.log have 0666 permissions

Is there any way to debug this? Can you give me some hints? For example - where I can find log where supervisord-monitor tries to get logs from server with Supervisord and without success?
Or, which permission requires RPC of Supervisord  to give logs to your supervisord-monitor?


P. S.  Already enabled logs with loglevel - all and didn't find any info in */supervisord-monitor/application/logs/

**Comment by sunliver** [comment]
@najamhaq @VStepulo   
Hey, I've solved this warning.

Check your supervisord.conf file.
eg.
[program:test]
process_name=%(program_name)s_%(process_num)02d
...
redirect_stderr=false
stdout_logfile=path_to_stdout_logfile
stderr_logfile=path_to_stderr_logfile

Notice that stderr_logfile is necessary for supervisord-monitor. And DONT set redirect_stderr to true . 
>If true, cause the process’ stderr output to be sent back to supervisord on its stdout file 
http://supervisord.org/configuration.html?highlight=redirect_stderr

**Comment by najamhaq** [comment]
This Worked @sunliver  :+1:  Thanks.

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
