### ISSUE TITLE
What's wrong with the  index.php file

### ISSUE THREAD

**Issue by zqbake** [mlazarov/supervisord-monitor#40]
When I open the browser I only get the warning:

Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

and here is the nginx congfig:

server
{
    listen 9000;
    server_name my_host;
    index index.php index.html index.htm default.php default.htm default.html;
    root /home/supervisord-monitor/public_html;
    location / {
                # Check if a file or directory index file exists, else route it to index.php.
                try_files $uri $uri/ /index.php;
        }

**Comment by mlazarov** [comment]
Hey zhqu1148980644,

check the [$system_path](https://github.com/mlazarov/supervisord-monitor/blob/master/public_html/index.php#L57) variable. Should point to the [system](https://github.com/mlazarov/supervisord-monitor/tree/master/system) directory on your server.

May be you moved this directory to somewhere else.

**Comment by zqbake** [comment]
thanks, sorry for the reply delayed.
