### ISSUE TITLE
Tracking workload

### ISSUE THREAD

**Issue by masterseo2000** [mlazarov/supervisord-monitor#41]
Hello,
Is there a way to also track workloads? Some workloads create exceptions but its very hard to stop the specific worker that is processing that workload. Any ideas how to manage this?
Thanks a lot!

**Comment by mlazarov** [comment]
Can you give me more details?

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
