### ISSUE TITLE
any suggestions?

### ISSUE THREAD

**Issue by felixzh2020** [mlazarov/supervisord-monitor#43]
![360 20180413161152204](https://user-images.githubusercontent.com/16359007/38724013-88425cb6-3f35-11e8-828d-a855af8a9560.jpg)
@johncongdon @disc @notFloran @mlazarov @TiagoGouvea

**Comment by felixzh2020** [comment]
#17

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
