### ISSUE TITLE
Routing problem for numeric process_name

### ISSUE THREAD

**Issue by costasovo** [mlazarov/supervisord-monitor#44]
We often use more than one process of supervisord program and we have supervisor configured so that `process_name=%(process_num)02d` (see  [supervisord docs](http://supervisord.org/configuration.html#program-x-section-settings))

This setup causes that button links for starting, stopping and restarting single process are for example:
`https://superv-monitor.com/control/stop/10/email_process:01` and it seems that every link which ends with number after `:` is evaluated by router as a base url and welcome.php is rendered without any action.

This works fine: `https://superv-monitor.com/control/stop/10/email_process:p01`

**Comment by hakuno** [comment]
Did you test with URL encoding?

See `https://superv-monitor.com/control/stop/10/email_process%3A01`

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
