### ISSUE TITLE
Does it support read logs?

### ISSUE THREAD

**Issue by potoo0** [mlazarov/supervisord-monitor#51]
Does it support read logs? such as stdout.log, stderr.log

**Comment by mlazarov** [comment]
Only last few lines from `stderr log`.

**Comment by potoo0** [comment]
Thanks, but I cann't find where it is. T_T

**Comment by mlazarov** [comment]
If there is anything in stderr you will see yellow warning on red background. Like the one on 
`server01` => `process05` 

![Screenshot](https://raw.github.com/mlazarov/supervisord-monitor/master/supervisord-monitor.png)

**Comment by potoo0** [comment]
OK, got it, Thank u.

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
