### ISSUE TITLE
The requested URL /control* not found

### ISSUE THREAD

**Issue by armenr** [mlazarov/supervisord-monitor#6]
Hi there - First off, let me just say that I absolutely love this tool. It's excellent. 

I can view my supervisor nodes, and they show up in the dash. I can see their uptime and their status, but when I try to control a node by starting/stopping it, I get a 404. 

Apache logs:
127.0.0.1 - - [19/Aug/2014:11:13:59 -0700] "GET /control/stop/dev1/fire HTTP/1.1" 404 529

Not Found
The requested URL /control/stop/dev1/fire was not found on this server.

The same 404 is thrown when I try to "clear" the status/alert. 

127.0.0.1 - - [19/Aug/2014:11:15:48 -0700] "GET /control/clear/dev1/fire HTTP/1.1" 404 530

I know the supervisor.php is configured correctly and the auth is accepted on the host side because I see the list of supervisor processes and their status/uptime. 

Any help would be much appreciated. Thanks!

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
