### ISSUE TITLE
Rewrite with some improvements

### ISSUE THREAD

**Issue by sagikazarmark** [mlazarov/supervisord-monitor#9]
Hey @mlazarov 

I sent you an email about some improvements (and also a rewrite) idea. Thought posting it here is a good idea:
- Rewrite using a micro framework (eg. https://github.com/alexbilbie/Proton)
- Store credentials in yml, so that opcode cache does not cause any problem
- Upgrade to TWBS 3
- Use [SupervisorPHP](https://github.com/supervisorphp/supervisor) as a client
- Optional team up with [SupervisorPHP](http://supervisorphp.com) (Full disclosure: I am the author)

What do you think?

**Comment by mlazarov** [comment]
Hi sagikazarmark,

why to rewrite to some other framework?

**Comment by sagikazarmark** [comment]
As I explained in the email, I think Codeigniter is a huge overkill for such an application. You obviously won't need 85% of it. Also, it would be faster with a lightview framework than a fully featured MVC one. And the last reason I can think of: the repository itself would be much lighter.

**Comment by sagikazarmark** [comment]
Sorry if I seemed to be rude, didn't mean to. You did an awesome work, but I think there is always room for improvement. Even if we see it different ways.

**Comment by mlazarov** [comment]
Yes, there is aways room for improvements, but moving from one framework to another to win a few ms of time is big overkill :) Using CI this app was done for a less than half an hour and if you can do this with Proton will be great.

**Comment by sagikazarmark** [comment]
It is not just about speed.

If I rewrite this to a Proton application using SupervisorPHP as a client, would you join in development?

**Comment by mlazarov** [comment]
Thanks for the opportunity. I really appreciate it. I have too much on my plate right now, but I’d be happy to reconsider once I get the chance.

**Comment by sagikazarmark** [comment]
Well, I am not asking to drop support for the current one. What I imagined is that we team up, keep a legacy branch for bugfixing the current application and maintaining a rewritten application. I am going to rewrite now implementing the main features of this one. Will discuss it later then. ;)

**Comment by sagikazarmark** [comment]
Here is what I've done so far:
https://github.com/supervisorphp/monitor

**Comment by KoNekoD** [comment]
This project has been abandoned. I would like to recommend mine, it is more modern https://github.com/KoNekoD/supervisord-monitor
